# version: '3.8'

# services:
#   # redis:
#   #   image: redis:7
#   #   ports:
#   #     - "6379:6379"
#   #   restart: unless-stopped

#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     env_file:
#       - .env
#     # depends_on:
#     #   - redis
#     ports:
#       - "8000:8000"
#     restart: unless-stopped
#     environment:
#       #-  SHIELD_AI_REDIS_HOST=redis
#       - SHIELD_AI_REDIS_HOST=host.docker.internal
#     networks:
#       - app-network

#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile.frontend
#     env_file:
#       - .env
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend
#     restart: unless-stopped
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge


version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge