global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@shield-ai.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://host.docker.internal:8000/api/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alert_user'
            password: 'alert_password'

  - name: 'email-alerts'
    email_configs:
      - to: 'admin@shield-ai.com'
        html: |
          <h3>Shield AI Alert: {{ .GroupLabels.alertname }}</h3>
          {{ range .Alerts }}
          <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']